### ISSUE TITLE
Update MNP Script

### ISSUE THREAD

**Issue by MNPSido** [MasterNodesPro/MNPCoin#18]
Here the link

https://raw.githubusercontent.com/MasterNodesPro/MNPCoin/master/doc/masternode.sh

there is still old walletlink inside
wget https://github.com/MasterNodesPro/MNPCoin/releases/download/v1.1.0/mnpcoin-linux-ubuntu1604-v1.1.0.zip -O mnpcoin-v1.1.0.zip

pls Change to new walletversion

**Comment by MNPJason** [comment]
This has been completed
